### ISSUE TITLE
spurious "islands_car" on highway=track connected with other highway=track

### ISSUE THREAD

**Issue by matkoniecz** [geofabrik/osmi_routing#14]
https://www.openstreetmap.org/way/739055022

<html><body>

2546. | WAY | 739055022 | routing | islands_car (?) | 2022-01-10 03:33:50.846 | 76262885
-- | -- | -- | -- | -- | -- | --

</body>
</html>

1) considering `highway=track` without further tags as car accessible is quite brave

2) https://www.openstreetmap.org/way/580186288 -> https://www.openstreetmap.org/way/445154307 -> https://www.openstreetmap.org/way/180957245#map=19/49.60875/19.49640 are connecting to roads in general

**Comment by Nakaner** [comment]
The `CarFlagEncoder` decides which ways make it up into the graph. We try to be in line with upstream GraphHopper's flag encoders as much as possible. Therefore, this is a wontfix issue.
