### ISSUE TITLE
multireport - the same way appears many times with the same error

### ISSUE THREAD

**Issue by matkoniecz** [geofabrik/osmi_routing#16]
https://resultmaps.neis-one.org/hdyc-osmi-issues?uid=1722488

<html><body>

1689. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
-- | -- | -- | -- | -- | -- | --
1690. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1691. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1692. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1693. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1694. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1695. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1696. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1697. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1698. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1699. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1700. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1701. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
1702. | WAY | 292448872 | routing | islands_all (?) | 2022-01-10 03:34:26.524 | 24104942
 

</body>
</html>

<html><body>

1770. | WAY | 300048197 | routing | islands_all (?) | 2022-01-10 03:34:26.904 | 90987892
-- | -- | -- | -- | -- | -- | --
1771. | WAY | 300048197 | routing | islands_all (?) | 2022-01-10 03:34:26.904 | 90987892

</body>
</html>

<html><body>

2173. | WAY | 516102280 | routing | islands_all (?) | 2022-01-10 03:34:27.361 | 68831396
-- | -- | -- | -- | -- | -- | --
2174. | WAY | 516102280 | routing | islands_all (?) | 2022-01-10 03:34:27.361 | 68831396
2175. | WAY | 516102280 | routing | islands_all (?) | 2022-01-10 03:34:27.361 | 68831396

</body>
</html>

**Comment by Nakaner** [comment]
14 occurrences in the list would be fine because ways are splitted up by GraphHopper into edges during preprocessing. OSMI Routing works on graph level, not OSM way level. Therefore, the same way can be reported multiple times.

I am sorry to tell you that missing deduplication by HDYC is not considered an OSMI issue.
