### ISSUE TITLE
Does not route over areas

### ISSUE THREAD

**Issue by amandasaurus** [geofabrik/osmi_routing#2]
The `highway=footway` [way 304055919](https://www.openstreetmap.org/way/304055919) is incorrectly marked as a routing island. But it's connected to [this car park](https://www.openstreetmap.org/way/304058150), which is connected to [this service road](https://www.openstreetmap.org/way/87046684). 

The software should recongise that people can walk across a car park, and hence walk to the footway and hence that it's not a routing island.

**Comment by Nakaner** [comment]
`amenity=parking` + `area=yes` is not considered as an routeable area. Neither routing over it like over a `highway=pedestrian` + `area=yes` nor routing along its edges seems sensible to me. Therefore, this is a mapping error requiring parking aisles or footways to be added inside the car park.
