### ISSUE TITLE
Confusing supposed island

### ISSUE THREAD

**Issue by matkoniecz** [geofabrik/osmi_routing#29]
https://www.openstreetmap.org/way/161023908 is according to https://resultmaps.neis-one.org/hdyc-osmi-issues?uid=1722488 problematic

looking at OSM data I am confused what is supposed to be the problem

https://tools.geofabrik.de/osmi/?view=routing&lon=19.96263&lat=50.04327&zoom=19&baselayer=Geofabrik%20Standard&overlays=duplicated_edges%2Cduplicated_edges%2Cduplicated_edges_areas%2Cislands%2Cislands_car%2Cislands_bicycle%2Cislands_all%2Csnap_points%2Cunconnected_open_ends_1%2Cunconnected_open_ends_2%2Cunconnected_open_ends_3%2Cunconnected_open_ends_4%2Cunconnected_open_ends_5%2Cunconnected_open_ends_6%2Cduplicated_edges%2Cduplicated_edges%2Cduplicated_edges_areas%2Cislands%2Cislands_car%2Cislands_bicycle%2Cislands_all%2Csnap_points%2Cunconnected_open_ends_1%2Cunconnected_open_ends_2%2Cunconnected_open_ends_3%2Cunconnected_open_ends_4%2Cunconnected_open_ends_5%2Cunconnected_open_ends_6 shows green way not matching any geometry in OSM

![screen04](https://github.com/geofabrik/osmi_routing/assets/899988/e1e00d9e-053b-45e6-aabf-77f38beadd29)

**Comment by vmicho** [comment]
there is a block there and the path is highlighted from that block.
If the track is not for cars, just add motor_vehicles=no to the whole track.

**Comment by matkoniecz** [comment]
oh, thanks!

https://www.openstreetmap.org/note/4494618
